### ISSUE TITLE
Create a design

### ISSUE THREAD

**Issue by chriseidhof** [chriseidhof/pomotv#7]
This is just the default middleman css file. We should have something that looks great.

**Comment by bontoJR** [comment]
I created a dedicated branch and pushed a proposal. It's from Pure.css, I really like that framework because is very slim and easy to use. Branch name: [ui-design](https://github.com/chriseidhof/ios-videos/tree/ui-design).

Screenshot:
<img width="1112" alt="screen shot 2015-12-17 at 23 48 51" src="https://cloud.githubusercontent.com/assets/159493/11884480/655acb50-a51a-11e5-898a-0d99f2ccbff4.png">

**Comment by chriseidhof** [comment]
Awesome! This is much better than what we currently have. It'd be nice to have a real designer have a look at it someday. But until then, this is a huge improvement. Mind opening a PR? Is this otherwise ready to merge?

**Comment by bontoJR** [comment]
Glad you liked.

I am on duty service today, it's merge-ready, so you can go ahead if you want, I would not be able to do it today.

Of course a future re-design by a professional is more than welcomed.

**Comment by johankj** [comment]
It’s a good start.
I have merged it into the main branch.

**Comment by chriseidhof** [comment]
Awesome!
